# Generated by Django 3.2.12 on 2022-04-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicase', '0002_rapositionpost'),
        ('applicase', '0003_auto_20220406_0209'),
    ]

    operations = [
    ]
