# Generated by Django 3.2.12 on 2022-02-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicase', '0003_auto_20220220_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='case_id',
            field=models.CharField(default='pcr30', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='case_id',
            field=models.CharField(default='pcr30', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
