# Generated by Django 3.2.12 on 2022-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicase', '0004_merge_0002_rapositionpost_0003_auto_20220406_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapositionpost',
            name='department',
            field=models.CharField(default='other', max_length=45),
        ),
        migrations.CreateModel(
            name='StudentInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('interest', models.CharField(max_length=45)),
            ],
            options={
                'unique_together': {('username', 'interest')},
            },
        ),
    ]
