# Generated by Django 3.2.12 on 2022-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicase', '0004_auto_20220220_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='case_id',
            field=models.CharField(max_length=10),
        ),
    ]
