# Generated by Django 3.2.12 on 2022-04-17 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicase', '0005_auto_20220417_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAPositionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(related_name='chat_members', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicase.tapositionpost')),
            ],
        ),
    ]
