# Generated by Django 3.2.12 on 2022-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicase', '0006_remove_tapositionpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(default='XXXX', max_length=50),
        ),
    ]
